### PR TITLE
Added joint, wireframe, COM, Inertia overlay

### PR DESCRIPTION
**Pull request by rohit-kumar-j**
Joint overlay added with "J"

joint_overlay_gif

### CODE REVIEW

**Comment by rohit-kumar-j** [comment]
Added Wireframe rendering with "W"

wire_frame_rendering_mujoco

**Comment by rohit-kumar-j** [comment]
**COM:**
com_rendering_mujoco

**INERTIA:**
inertia_rendering_mujoco

**Comment by rohanpsingh** [comment]
Looks good, thanks for the PR!

**Comment by rohanpsingh** [comment]
Assuming, mjVIS_CONTACTFORCE was removed inadvertently, I'll add that line again manually.

**Comment by rohit-kumar-j** [comment]
mjVIS_CONTACTFORCE was written twice, so I reduced it

**Comment by rohit-kumar-j** [comment]
I wanted to add _convex hull_ as well, but didn't really know how to work with the documentation in C. The [mjVIS_CONVEXHULL is equal to 0](https://github.com/deepmind/mujoco/blob/87539dbd24825249f6215fb43050d4dd2c9a8fc2/include/mjvisualize.h#L99). I saw the [vopt.frame](https://github.com/rohanpsingh/mujoco-python-viewer/blob/e65843c1e5d0fa7bcecb49b18600a40ac88e9746/mujoco_viewer/mujoco_viewer.py#L121) and tried the same but didn't work. Do you have any pointers to example python bindings examples like the [Pybullet Quickstart Guide](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#heading=h.2ye70wns7io3)

**Comment by rohanpsingh** [comment]
> mjVIS_CONTACTFORCE was written twice, so I reduced it

The first line was for `mjVIS_CONTACTPOINT` followed by the line for `mjVIS_CONTACTFORCE`. Their purpose is different.


> I wanted to add convex hull as well, but didn't really know how to work with the documentation in C.

Let me see if I can get it working.

**Comment by rohit-kumar-j** [comment]
> The first line was for `mjVIS_CONTACTPOINT` followed by the line for `mjVIS_CONTACTFORCE`. Their purpose is different.


Ah. I missed that

**Comment by rohit-kumar-j** [comment]
PR #7  with Convex Hull

**Pull request merged**
